### ISSUE TITLE
queries.listPhotosByAlbum returns no results. Cannot retrieve images.

### ISSUE THREAD

**Issue by jakeane** [aws-samples/amplify-photo-gallery-workshop#46] opened 2020-07-29 19:31 UTC
Hi all,

I followed your tutorial on [amplify-workshop.go-aws.com](https://amplify-workshop.go-aws.com/) and ran into a set of issues. I also cloned and ran this repo and arrived at the same issues.

Some of the GraphQL queries work just fine. Like I can create and navigate between albums just fine, but querying for photos within an album does not work for me. To show, I logged the results from the queries.listPhotosByAlbum in fetchNextPhotos (line 171), like so.
```javascript
 const results = await API.graphql(graphqlOperation(queries.listPhotosByAlbum, queryArgs));
 console.log(results);
 setPhotos(p => p.concat(results.data.listPhotosByAlbum.items));
```
In the console, I got an empty list from results.data.listPhotosByAlbum.items. This is unexpected as I have populated the album with plenty of photos, so I am not entirely sure why this is the case.

I have spent some time trying to further understand the cause of this issue, so here are some potential causes given my beginner understanding of AWS and GraphQL:
* As I have been running the cloned code without success, there may be an issue with my AWS project/bucket. I have given the contentbucket complete public access, thinking that it was a restricted access issue, but that did not change anything. However, I would not be surprised if I am missing something on that front.
* There may be a possible albumId mismatch. I also logged the queryArgs from the snippet above, and the album id does not seem to match with anything within the contentbucket. However, the uploaded file id does seem to match with content in the bucket.
* The last idea I have is that there is something wrong with the GraphQL schema, but my understanding of GraphQL is so little that I cannot attempt to diagnose this.

Let me know if you need any more info or context around this issue. I would be happy to share my AWS project as well.

Thanks,
Jack

**Comment by gabehollombe-aws** [comment] 2020-08-12 02:30
> In the console, I got an empty list from results.data.listPhotosByAlbum.items. This is unexpected as I have populated the album with plenty of photos, so I am not entirely sure why this is the case.

Hmm...  Can you confirm that you have entries in your the associated Photos table in DynamoDB, and that they have an album id that points to the ID of the Album you expect to see them in?

**Comment by iaminawe** [comment] 2020-09-10 17:58
I can confirm the same issue. I have tried this by setting it up step by step following the instructions and have also tried with the cloned repository and I get the same result as Jack.

When I view the dynamo db table for photos it is empty and when I check the S3 bucket there are no thumbnails being generated. I checked the logs for the Lambda TriggerS3 function and see it is firing but no thumbnails or db entries are being made.

Steps to reproduce:
1.) Cloned repo
2.) cd into photoalbums folder
3.) npm install
4.) amplify init
5.) amplify push and wait for completion
6.) npm start
7.) create user account, verify and login with it
8.) create album
9.) click into album and upload photo
10.) confirm that console shows log that photo upload is successful
11.) check S3 folder and see new image but not derivatives
12.) check db tables and see album but not photos

Any assistance would be greatly appreciated

Thanks
Gregg

**Comment by gabehollombe-aws** [comment] 2020-09-11 03:23
Thanks for an additional report, @iaminawe  -- I've booked time in my calendar next week to dive in to this.  I hope to have an answer for you in the next few working days.

**Comment by gabehollombe-aws** [comment] 2020-09-14 02:58
@iaminawe and @jakeane Thanks for your patience. I went through the workshop this morning, following the steps along the way, and I was not able to reproduce the issue you're reporting.  

I recorded my runthrough and you can watch it here: https://youtu.be/GAf37PbD4QI -- Note: there are a few steps in the recording where my Cloud9 instance ran out of disk space (this is new, likely JS lib bloat in transitive NPM dependencies, but I just cleared up some unused files and was able to proceed).

You can jump the end at time 38:12 https://youtu.be/GAf37PbD4QI?t=2292 to see me uploading photos and having their thumbnails appear in the album.

Now, this probably means there's some instructional step in the workshop that's not obvious enough and I have an opportunity to make it better. We just need to figure out what that is.  Could you please skim the video and compare the steps I took to your own actions to see if you can figure out what you did differently, if anything?

Of course, it could also be that I'm misunderstanding your issue, so please let me know if I've missed the problem completely here.

I'll leave this issue open for a bit in hopes that you can reply with more info to help me improve the instructions. Thank you!

**Comment by 404Kartik** [comment] 2020-10-11 16:31
This is kinda weird when I follow your video tutorial I was able to develop it and I did not have any issues with the workshop at all, we are definitely missing something very minute in the lab manual.
@gabehollombe-aws I will take some time out this week and try to figure out what's wrong with the lab manual.
I'd request you to keep the issue open
Stay safe
Kartik

**Comment by gabehollombe-aws** [comment] 2020-11-17 07:03
Closing this old thread.

**Closed as completed by gabehollombe-aws** 2020-11-17 07:03 UTC
